# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test_window.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QPushButton, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1033, 627)
        self.meaning_ilst_1 = QListWidget(Form)
        self.meaning_ilst_1.setObjectName(u"meaning_ilst_1")
        self.meaning_ilst_1.setGeometry(QRect(140, 30, 121, 591))
        font = QFont()
        font.setPointSize(10)
        self.meaning_ilst_1.setFont(font)
        self.meaning_ilst_2 = QListWidget(Form)
        self.meaning_ilst_2.setObjectName(u"meaning_ilst_2")
        self.meaning_ilst_2.setGeometry(QRect(560, 30, 121, 591))
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(840, 420, 181, 81))
        font1 = QFont()
        font1.setPointSize(20)
        self.pushButton.setFont(font1)
        self.Time_limit = QLabel(Form)
        self.Time_limit.setObjectName(u"Time_limit")
        self.Time_limit.setGeometry(QRect(850, 380, 181, 41))
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        self.Time_limit.setFont(font2)
        self.Time_limit.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.kr_answer_1 = QLineEdit(Form)
        self.kr_answer_1.setObjectName(u"kr_answer_1")
        self.kr_answer_1.setGeometry(QRect(270, 29, 141, 21))
        self.kr_answer_2 = QLineEdit(Form)
        self.kr_answer_2.setObjectName(u"kr_answer_2")
        self.kr_answer_2.setGeometry(QRect(270, 60, 141, 20))
        self.kr_answer_3 = QLineEdit(Form)
        self.kr_answer_3.setObjectName(u"kr_answer_3")
        self.kr_answer_3.setGeometry(QRect(270, 90, 141, 20))
        self.kr_answer_4 = QLineEdit(Form)
        self.kr_answer_4.setObjectName(u"kr_answer_4")
        self.kr_answer_4.setGeometry(QRect(270, 120, 141, 20))
        self.kr_answer_5 = QLineEdit(Form)
        self.kr_answer_5.setObjectName(u"kr_answer_5")
        self.kr_answer_5.setGeometry(QRect(270, 150, 141, 20))
        self.kr_answer_6 = QLineEdit(Form)
        self.kr_answer_6.setObjectName(u"kr_answer_6")
        self.kr_answer_6.setGeometry(QRect(270, 180, 141, 20))
        self.kr_answer_7 = QLineEdit(Form)
        self.kr_answer_7.setObjectName(u"kr_answer_7")
        self.kr_answer_7.setGeometry(QRect(270, 210, 141, 20))
        self.kr_answer_8 = QLineEdit(Form)
        self.kr_answer_8.setObjectName(u"kr_answer_8")
        self.kr_answer_8.setGeometry(QRect(270, 240, 141, 20))
        self.kr_answer_9 = QLineEdit(Form)
        self.kr_answer_9.setObjectName(u"kr_answer_9")
        self.kr_answer_9.setGeometry(QRect(270, 270, 141, 20))
        self.kr_answer_10 = QLineEdit(Form)
        self.kr_answer_10.setObjectName(u"kr_answer_10")
        self.kr_answer_10.setGeometry(QRect(270, 300, 141, 20))
        self.kr_answer_11 = QLineEdit(Form)
        self.kr_answer_11.setObjectName(u"kr_answer_11")
        self.kr_answer_11.setGeometry(QRect(270, 330, 141, 20))
        self.kr_answer_12 = QLineEdit(Form)
        self.kr_answer_12.setObjectName(u"kr_answer_12")
        self.kr_answer_12.setGeometry(QRect(270, 360, 141, 20))
        self.kr_answer_13 = QLineEdit(Form)
        self.kr_answer_13.setObjectName(u"kr_answer_13")
        self.kr_answer_13.setGeometry(QRect(270, 390, 141, 20))
        self.kr_answer_14 = QLineEdit(Form)
        self.kr_answer_14.setObjectName(u"kr_answer_14")
        self.kr_answer_14.setGeometry(QRect(270, 420, 141, 20))
        self.kr_answer_15 = QLineEdit(Form)
        self.kr_answer_15.setObjectName(u"kr_answer_15")
        self.kr_answer_15.setGeometry(QRect(270, 450, 141, 20))
        self.kr_answer_16 = QLineEdit(Form)
        self.kr_answer_16.setObjectName(u"kr_answer_16")
        self.kr_answer_16.setGeometry(QRect(270, 480, 141, 20))
        self.kr_answer_17 = QLineEdit(Form)
        self.kr_answer_17.setObjectName(u"kr_answer_17")
        self.kr_answer_17.setGeometry(QRect(270, 510, 141, 20))
        self.kr_answer_18 = QLineEdit(Form)
        self.kr_answer_18.setObjectName(u"kr_answer_18")
        self.kr_answer_18.setGeometry(QRect(270, 540, 141, 20))
        self.kr_answer_19 = QLineEdit(Form)
        self.kr_answer_19.setObjectName(u"kr_answer_19")
        self.kr_answer_19.setGeometry(QRect(270, 570, 141, 20))
        self.kr_answer_20 = QLineEdit(Form)
        self.kr_answer_20.setObjectName(u"kr_answer_20")
        self.kr_answer_20.setGeometry(QRect(270, 600, 141, 20))
        self.kr_answer_21 = QLineEdit(Form)
        self.kr_answer_21.setObjectName(u"kr_answer_21")
        self.kr_answer_21.setGeometry(QRect(690, 30, 141, 20))
        self.kr_answer_22 = QLineEdit(Form)
        self.kr_answer_22.setObjectName(u"kr_answer_22")
        self.kr_answer_22.setGeometry(QRect(690, 60, 141, 20))
        self.kr_answer_23 = QLineEdit(Form)
        self.kr_answer_23.setObjectName(u"kr_answer_23")
        self.kr_answer_23.setGeometry(QRect(690, 90, 141, 20))
        self.kr_answer_24 = QLineEdit(Form)
        self.kr_answer_24.setObjectName(u"kr_answer_24")
        self.kr_answer_24.setGeometry(QRect(690, 120, 141, 20))
        self.kr_answer_25 = QLineEdit(Form)
        self.kr_answer_25.setObjectName(u"kr_answer_25")
        self.kr_answer_25.setGeometry(QRect(690, 150, 141, 20))
        self.kr_answer_26 = QLineEdit(Form)
        self.kr_answer_26.setObjectName(u"kr_answer_26")
        self.kr_answer_26.setGeometry(QRect(690, 180, 141, 20))
        self.kr_answer_27 = QLineEdit(Form)
        self.kr_answer_27.setObjectName(u"kr_answer_27")
        self.kr_answer_27.setGeometry(QRect(690, 210, 141, 20))
        self.kr_answer_28 = QLineEdit(Form)
        self.kr_answer_28.setObjectName(u"kr_answer_28")
        self.kr_answer_28.setGeometry(QRect(690, 240, 141, 20))
        self.kr_answer_29 = QLineEdit(Form)
        self.kr_answer_29.setObjectName(u"kr_answer_29")
        self.kr_answer_29.setGeometry(QRect(690, 270, 141, 20))
        self.kr_answer_30 = QLineEdit(Form)
        self.kr_answer_30.setObjectName(u"kr_answer_30")
        self.kr_answer_30.setGeometry(QRect(690, 300, 141, 20))
        self.kr_answer_31 = QLineEdit(Form)
        self.kr_answer_31.setObjectName(u"kr_answer_31")
        self.kr_answer_31.setGeometry(QRect(690, 330, 141, 20))
        self.kr_answer_32 = QLineEdit(Form)
        self.kr_answer_32.setObjectName(u"kr_answer_32")
        self.kr_answer_32.setGeometry(QRect(690, 360, 141, 20))
        self.kr_answer_33 = QLineEdit(Form)
        self.kr_answer_33.setObjectName(u"kr_answer_33")
        self.kr_answer_33.setGeometry(QRect(690, 390, 141, 20))
        self.kr_answer_34 = QLineEdit(Form)
        self.kr_answer_34.setObjectName(u"kr_answer_34")
        self.kr_answer_34.setGeometry(QRect(690, 420, 141, 20))
        self.kr_answer_35 = QLineEdit(Form)
        self.kr_answer_35.setObjectName(u"kr_answer_35")
        self.kr_answer_35.setGeometry(QRect(690, 450, 141, 20))
        self.kr_answer_36 = QLineEdit(Form)
        self.kr_answer_36.setObjectName(u"kr_answer_36")
        self.kr_answer_36.setGeometry(QRect(690, 480, 141, 20))
        self.kr_answer_37 = QLineEdit(Form)
        self.kr_answer_37.setObjectName(u"kr_answer_37")
        self.kr_answer_37.setGeometry(QRect(690, 510, 141, 20))
        self.kr_answer_38 = QLineEdit(Form)
        self.kr_answer_38.setObjectName(u"kr_answer_38")
        self.kr_answer_38.setGeometry(QRect(690, 540, 141, 20))
        self.kr_answer_39 = QLineEdit(Form)
        self.kr_answer_39.setObjectName(u"kr_answer_39")
        self.kr_answer_39.setGeometry(QRect(690, 570, 141, 20))
        self.kr_answer_40 = QLineEdit(Form)
        self.kr_answer_40.setObjectName(u"kr_answer_40")
        self.kr_answer_40.setGeometry(QRect(690, 600, 141, 20))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 0, 61, 31))
        font3 = QFont()
        font3.setPointSize(14)
        self.label.setFont(font3)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(170, 0, 61, 31))
        self.label_2.setFont(font3)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(590, 0, 61, 31))
        self.label_3.setFont(font3)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(470, 0, 61, 31))
        self.label_4.setFont(font3)
        self.Word_11 = QLabel(Form)
        self.Word_11.setObjectName(u"Word_11")
        self.Word_11.setGeometry(QRect(30, 330, 101, 21))
        font4 = QFont()
        font4.setPointSize(12)
        self.Word_11.setFont(font4)
        self.Word_11.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_14 = QLabel(Form)
        self.Word_14.setObjectName(u"Word_14")
        self.Word_14.setGeometry(QRect(30, 420, 101, 21))
        self.Word_14.setFont(font4)
        self.Word_14.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_18 = QLabel(Form)
        self.Word_18.setObjectName(u"Word_18")
        self.Word_18.setGeometry(QRect(30, 540, 101, 21))
        self.Word_18.setFont(font4)
        self.Word_18.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_3 = QLabel(Form)
        self.Word_3.setObjectName(u"Word_3")
        self.Word_3.setGeometry(QRect(30, 90, 101, 21))
        self.Word_3.setFont(font4)
        self.Word_3.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_5 = QLabel(Form)
        self.Word_5.setObjectName(u"Word_5")
        self.Word_5.setGeometry(QRect(30, 150, 101, 21))
        self.Word_5.setFont(font4)
        self.Word_5.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_20 = QLabel(Form)
        self.Word_20.setObjectName(u"Word_20")
        self.Word_20.setGeometry(QRect(30, 600, 101, 21))
        self.Word_20.setFont(font4)
        self.Word_20.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_2 = QLabel(Form)
        self.Word_2.setObjectName(u"Word_2")
        self.Word_2.setGeometry(QRect(30, 60, 101, 21))
        self.Word_2.setFont(font4)
        self.Word_2.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_16 = QLabel(Form)
        self.Word_16.setObjectName(u"Word_16")
        self.Word_16.setGeometry(QRect(30, 480, 101, 21))
        self.Word_16.setFont(font4)
        self.Word_16.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_17 = QLabel(Form)
        self.Word_17.setObjectName(u"Word_17")
        self.Word_17.setGeometry(QRect(30, 510, 101, 21))
        self.Word_17.setFont(font4)
        self.Word_17.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_12 = QLabel(Form)
        self.Word_12.setObjectName(u"Word_12")
        self.Word_12.setGeometry(QRect(30, 360, 101, 21))
        self.Word_12.setFont(font4)
        self.Word_12.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_4 = QLabel(Form)
        self.Word_4.setObjectName(u"Word_4")
        self.Word_4.setGeometry(QRect(30, 120, 101, 21))
        self.Word_4.setFont(font4)
        self.Word_4.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_9 = QLabel(Form)
        self.Word_9.setObjectName(u"Word_9")
        self.Word_9.setGeometry(QRect(30, 270, 101, 21))
        self.Word_9.setFont(font4)
        self.Word_9.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_1 = QLabel(Form)
        self.Word_1.setObjectName(u"Word_1")
        self.Word_1.setGeometry(QRect(30, 30, 101, 21))
        self.Word_1.setFont(font4)
        self.Word_1.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_13 = QLabel(Form)
        self.Word_13.setObjectName(u"Word_13")
        self.Word_13.setGeometry(QRect(30, 390, 101, 21))
        self.Word_13.setFont(font4)
        self.Word_13.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_8 = QLabel(Form)
        self.Word_8.setObjectName(u"Word_8")
        self.Word_8.setGeometry(QRect(30, 240, 101, 21))
        self.Word_8.setFont(font4)
        self.Word_8.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_15 = QLabel(Form)
        self.Word_15.setObjectName(u"Word_15")
        self.Word_15.setGeometry(QRect(30, 450, 101, 21))
        self.Word_15.setFont(font4)
        self.Word_15.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_7 = QLabel(Form)
        self.Word_7.setObjectName(u"Word_7")
        self.Word_7.setGeometry(QRect(30, 210, 101, 21))
        self.Word_7.setFont(font4)
        self.Word_7.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_19 = QLabel(Form)
        self.Word_19.setObjectName(u"Word_19")
        self.Word_19.setGeometry(QRect(30, 570, 101, 21))
        self.Word_19.setFont(font4)
        self.Word_19.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_6 = QLabel(Form)
        self.Word_6.setObjectName(u"Word_6")
        self.Word_6.setGeometry(QRect(30, 180, 101, 21))
        self.Word_6.setFont(font4)
        self.Word_6.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_10 = QLabel(Form)
        self.Word_10.setObjectName(u"Word_10")
        self.Word_10.setGeometry(QRect(30, 300, 101, 21))
        self.Word_10.setFont(font4)
        self.Word_10.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_28 = QLabel(Form)
        self.Word_28.setObjectName(u"Word_28")
        self.Word_28.setGeometry(QRect(450, 240, 101, 21))
        self.Word_28.setFont(font4)
        self.Word_28.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_22 = QLabel(Form)
        self.Word_22.setObjectName(u"Word_22")
        self.Word_22.setGeometry(QRect(450, 60, 101, 21))
        self.Word_22.setFont(font4)
        self.Word_22.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_40 = QLabel(Form)
        self.Word_40.setObjectName(u"Word_40")
        self.Word_40.setGeometry(QRect(450, 600, 101, 21))
        self.Word_40.setFont(font4)
        self.Word_40.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_23 = QLabel(Form)
        self.Word_23.setObjectName(u"Word_23")
        self.Word_23.setGeometry(QRect(450, 90, 101, 21))
        self.Word_23.setFont(font4)
        self.Word_23.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_36 = QLabel(Form)
        self.Word_36.setObjectName(u"Word_36")
        self.Word_36.setGeometry(QRect(450, 480, 101, 21))
        self.Word_36.setFont(font4)
        self.Word_36.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_26 = QLabel(Form)
        self.Word_26.setObjectName(u"Word_26")
        self.Word_26.setGeometry(QRect(450, 180, 101, 21))
        self.Word_26.setFont(font4)
        self.Word_26.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_34 = QLabel(Form)
        self.Word_34.setObjectName(u"Word_34")
        self.Word_34.setGeometry(QRect(450, 420, 101, 21))
        self.Word_34.setFont(font4)
        self.Word_34.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_31 = QLabel(Form)
        self.Word_31.setObjectName(u"Word_31")
        self.Word_31.setGeometry(QRect(450, 330, 101, 21))
        self.Word_31.setFont(font4)
        self.Word_31.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_27 = QLabel(Form)
        self.Word_27.setObjectName(u"Word_27")
        self.Word_27.setGeometry(QRect(450, 210, 101, 21))
        self.Word_27.setFont(font4)
        self.Word_27.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_39 = QLabel(Form)
        self.Word_39.setObjectName(u"Word_39")
        self.Word_39.setGeometry(QRect(450, 570, 101, 21))
        self.Word_39.setFont(font4)
        self.Word_39.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_24 = QLabel(Form)
        self.Word_24.setObjectName(u"Word_24")
        self.Word_24.setGeometry(QRect(450, 120, 101, 21))
        self.Word_24.setFont(font4)
        self.Word_24.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_29 = QLabel(Form)
        self.Word_29.setObjectName(u"Word_29")
        self.Word_29.setGeometry(QRect(450, 270, 101, 21))
        self.Word_29.setFont(font4)
        self.Word_29.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_38 = QLabel(Form)
        self.Word_38.setObjectName(u"Word_38")
        self.Word_38.setGeometry(QRect(450, 540, 101, 21))
        self.Word_38.setFont(font4)
        self.Word_38.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_32 = QLabel(Form)
        self.Word_32.setObjectName(u"Word_32")
        self.Word_32.setGeometry(QRect(450, 360, 101, 21))
        self.Word_32.setFont(font4)
        self.Word_32.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_30 = QLabel(Form)
        self.Word_30.setObjectName(u"Word_30")
        self.Word_30.setGeometry(QRect(450, 300, 101, 21))
        self.Word_30.setFont(font4)
        self.Word_30.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_37 = QLabel(Form)
        self.Word_37.setObjectName(u"Word_37")
        self.Word_37.setGeometry(QRect(450, 510, 101, 21))
        self.Word_37.setFont(font4)
        self.Word_37.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_35 = QLabel(Form)
        self.Word_35.setObjectName(u"Word_35")
        self.Word_35.setGeometry(QRect(450, 450, 101, 21))
        self.Word_35.setFont(font4)
        self.Word_35.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_21 = QLabel(Form)
        self.Word_21.setObjectName(u"Word_21")
        self.Word_21.setGeometry(QRect(450, 30, 101, 21))
        self.Word_21.setFont(font4)
        self.Word_21.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_25 = QLabel(Form)
        self.Word_25.setObjectName(u"Word_25")
        self.Word_25.setGeometry(QRect(450, 150, 101, 21))
        self.Word_25.setFont(font4)
        self.Word_25.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.Word_33 = QLabel(Form)
        self.Word_33.setObjectName(u"Word_33")
        self.Word_33.setGeometry(QRect(450, 390, 101, 21))
        self.Word_33.setFont(font4)
        self.Word_33.setStyleSheet(u"QLabel {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 450, 31, 21))
        self.label_16.setFont(font4)
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 180, 31, 16))
        self.label_6.setFont(font4)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 120, 31, 21))
        self.label_5.setFont(font4)
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 480, 31, 21))
        self.label_15.setFont(font4)
        self.label_18 = QLabel(Form)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 540, 31, 21))
        self.label_18.setFont(font4)
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 390, 31, 21))
        self.label_13.setFont(font4)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 30, 31, 16))
        self.label_7.setFont(font4)
        self.label_20 = QLabel(Form)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 600, 31, 21))
        self.label_20.setFont(font4)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 150, 31, 16))
        self.label_8.setFont(font4)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 90, 31, 21))
        self.label_9.setFont(font4)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 210, 31, 16))
        self.label_10.setFont(font4)
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 60, 31, 21))
        self.label_11.setFont(font4)
        self.label_19 = QLabel(Form)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 570, 31, 21))
        self.label_19.setFont(font4)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 270, 31, 21))
        self.label_12.setFont(font4)
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 330, 31, 21))
        self.label_14.setFont(font4)
        self.label_17 = QLabel(Form)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 360, 31, 21))
        self.label_17.setFont(font4)
        self.label_21 = QLabel(Form)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 300, 31, 21))
        self.label_21.setFont(font4)
        self.label_22 = QLabel(Form)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(0, 510, 31, 21))
        self.label_22.setFont(font4)
        self.label_23 = QLabel(Form)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(0, 420, 31, 21))
        self.label_23.setFont(font4)
        self.label_24 = QLabel(Form)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 240, 31, 16))
        self.label_24.setFont(font4)
        self.label_28 = QLabel(Form)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(420, 90, 31, 21))
        self.label_28.setFont(font4)
        self.label_31 = QLabel(Form)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(420, 120, 31, 21))
        self.label_31.setFont(font4)
        self.label_36 = QLabel(Form)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(420, 390, 31, 21))
        self.label_36.setFont(font4)
        self.label_25 = QLabel(Form)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(420, 480, 31, 21))
        self.label_25.setFont(font4)
        self.label_30 = QLabel(Form)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(420, 150, 31, 16))
        self.label_30.setFont(font4)
        self.label_33 = QLabel(Form)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(420, 30, 31, 21))
        self.label_33.setFont(font4)
        self.label_34 = QLabel(Form)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(420, 360, 31, 21))
        self.label_34.setFont(font4)
        self.label_27 = QLabel(Form)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(420, 180, 31, 16))
        self.label_27.setFont(font4)
        self.label_26 = QLabel(Form)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(420, 450, 31, 21))
        self.label_26.setFont(font4)
        self.label_35 = QLabel(Form)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(420, 240, 31, 16))
        self.label_35.setFont(font4)
        self.label_29 = QLabel(Form)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(420, 300, 31, 21))
        self.label_29.setFont(font4)
        self.label_32 = QLabel(Form)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(420, 510, 31, 21))
        self.label_32.setFont(font4)
        self.label_37 = QLabel(Form)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(420, 210, 31, 16))
        self.label_37.setFont(font4)
        self.label_38 = QLabel(Form)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(420, 540, 31, 21))
        self.label_38.setFont(font4)
        self.label_39 = QLabel(Form)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(420, 570, 31, 21))
        self.label_39.setFont(font4)
        self.label_40 = QLabel(Form)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(420, 420, 31, 21))
        self.label_40.setFont(font4)
        self.label_41 = QLabel(Form)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(420, 330, 31, 21))
        self.label_41.setFont(font4)
        self.label_42 = QLabel(Form)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(420, 60, 31, 21))
        self.label_42.setFont(font4)
        self.label_43 = QLabel(Form)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(420, 270, 31, 21))
        self.label_43.setFont(font4)
        self.label_44 = QLabel(Form)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(420, 600, 31, 21))
        self.label_44.setFont(font4)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\ucc44\uc810\ud558\uae30", None))
        self.Time_limit.setText(QCoreApplication.translate("Form", u"00:00:00", None))
        self.label.setText(QCoreApplication.translate("Form", u"<\ub2e8\uc5b4>", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"<\uc758\ubbf8>", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"<\uc758\ubbf8>", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"<\ub2e8\uc5b4>", None))
        self.Word_11.setText("")
        self.Word_14.setText("")
        self.Word_18.setText("")
        self.Word_3.setText("")
        self.Word_5.setText("")
        self.Word_20.setText("")
        self.Word_2.setText("")
        self.Word_16.setText("")
        self.Word_17.setText("")
        self.Word_12.setText("")
        self.Word_4.setText("")
        self.Word_9.setText("")
        self.Word_1.setText("")
        self.Word_13.setText("")
        self.Word_8.setText("")
        self.Word_15.setText("")
        self.Word_7.setText("")
        self.Word_19.setText("")
        self.Word_6.setText("")
        self.Word_10.setText("")
        self.Word_28.setText("")
        self.Word_22.setText("")
        self.Word_40.setText("")
        self.Word_23.setText("")
        self.Word_36.setText("")
        self.Word_26.setText("")
        self.Word_34.setText("")
        self.Word_31.setText("")
        self.Word_27.setText("")
        self.Word_39.setText("")
        self.Word_24.setText("")
        self.Word_29.setText("")
        self.Word_38.setText("")
        self.Word_32.setText("")
        self.Word_30.setText("")
        self.Word_37.setText("")
        self.Word_35.setText("")
        self.Word_21.setText("")
        self.Word_25.setText("")
        self.Word_33.setText("")
        self.label_16.setText(QCoreApplication.translate("Form", u"15.", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"6.", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"4.", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"16.", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"18.", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"13.", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"1.", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"20.", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"5.", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"3.", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"7.", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"2.", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"19.", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"9.", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"11.", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"12.", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"10.", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"17.", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"14.", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"8.", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"23.", None))
        self.label_31.setText(QCoreApplication.translate("Form", u"24.", None))
        self.label_36.setText(QCoreApplication.translate("Form", u"33.", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"36.", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"25.", None))
        self.label_33.setText(QCoreApplication.translate("Form", u"21.", None))
        self.label_34.setText(QCoreApplication.translate("Form", u"32.", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"26.", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"35.", None))
        self.label_35.setText(QCoreApplication.translate("Form", u"28.", None))
        self.label_29.setText(QCoreApplication.translate("Form", u"30.", None))
        self.label_32.setText(QCoreApplication.translate("Form", u"37.", None))
        self.label_37.setText(QCoreApplication.translate("Form", u"27.", None))
        self.label_38.setText(QCoreApplication.translate("Form", u"38.", None))
        self.label_39.setText(QCoreApplication.translate("Form", u"39.", None))
        self.label_40.setText(QCoreApplication.translate("Form", u"34.", None))
        self.label_41.setText(QCoreApplication.translate("Form", u"31.", None))
        self.label_42.setText(QCoreApplication.translate("Form", u"22.", None))
        self.label_43.setText(QCoreApplication.translate("Form", u"29.", None))
        self.label_44.setText(QCoreApplication.translate("Form", u"40.", None))
    # retranslateUi

