words=[
    {"word": "abandon", "meaning": "포기하다"},
    {"word": "benefit", "meaning": "이익"},
    {"word": "consequence", "meaning": "결과"},
    {"word": "determine", "meaning": "결정하다"},
    {"word": "effort", "meaning": "노력"},
    {"word": "frequent", "meaning": "자주"},
    {"word": "generate", "meaning": "생성하다"},
    {"word": "harbor", "meaning": "항구"},
    {"word": "initial", "meaning": "처음의"},
    {"word": "justify", "meaning": "정당화하다"},
    {"word": "knowledge", "meaning": "지식"},
    {"word": "launch", "meaning": "출시하다"},
    {"word": "maintain", "meaning": "유지하다"},
    {"word": "narrow", "meaning": "좁은"},
    {"word": "occur", "meaning": "발생하다"},
    {"word": "participate", "meaning": "참여하다"},
    {"word": "question", "meaning": "질문"},
    {"word": "respond", "meaning": "응답하다"},
    {"word": "satisfy", "meaning": "만족시키다"},
    {"word": "transform", "meaning": "변화시키다"},
    {"word": "unique", "meaning": "독특한"},
    {"word": "victory", "meaning": "승리"},
    {"word": "wonder", "meaning": "궁금해하다"},
    {"word": "xenon", "meaning": "크세논"},
    {"word": "yearn", "meaning": "갈망하다"},
    {"word": "zeal", "meaning": "열정"},
    {"word": "anticipate", "meaning": "기대하다"},
    {"word": "believe", "meaning": "믿다"},
    {"word": "collaborate", "meaning": "협력하다"},
    {"word": "define", "meaning": "정의하다"},
    {"word": "elevate", "meaning": "높이다"},
    {"word": "facilitate", "meaning": "촉진하다"},
    {"word": "glimpse", "meaning": "흘끗 보다"},
    {"word": "hesitate", "meaning": "주저하다"},
    {"word": "inspire", "meaning": "영감을 주다"},
    {"word": "judge", "meaning": "판단하다"},
    {"word": "keen", "meaning": "열렬한"},
    {"word": "linger", "meaning": "오래 머물다"},
    {"word": "manifest", "meaning": "명백히 하다"},
    {"word": "negotiate", "meaning": "협상하다"}
]
print(words[2])
a=words
print(a[1])