# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ele.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QListWidget, QListWidgetItem,
    QPushButton, QSizePolicy, QTextEdit, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(606, 456)
        self.listWidget_2 = QListWidget(Form)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(110, 20, 61, 401))
        self.listWidget_4 = QListWidget(Form)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(340, 20, 71, 401))
        self.listWidget_3 = QListWidget(Form)
        self.listWidget_3.setObjectName(u"listWidget_3")
        self.listWidget_3.setGeometry(QRect(260, 20, 71, 401))
        self.listWidget_1 = QListWidget(Form)
        self.listWidget_1.setObjectName(u"listWidget_1")
        self.listWidget_1.setGeometry(QRect(30, 20, 71, 401))
        self.Korean_answer_1 = QTextEdit(Form)
        self.Korean_answer_1.setObjectName(u"Korean_answer_1")
        self.Korean_answer_1.setGeometry(QRect(180, 20, 71, 21))
        self.Korean_answer_4 = QTextEdit(Form)
        self.Korean_answer_4.setObjectName(u"Korean_answer_4")
        self.Korean_answer_4.setGeometry(QRect(180, 80, 71, 21))
        self.Korean_answer_5 = QTextEdit(Form)
        self.Korean_answer_5.setObjectName(u"Korean_answer_5")
        self.Korean_answer_5.setGeometry(QRect(180, 100, 71, 21))
        self.Korean_answer_2 = QTextEdit(Form)
        self.Korean_answer_2.setObjectName(u"Korean_answer_2")
        self.Korean_answer_2.setGeometry(QRect(180, 40, 71, 21))
        self.Korean_answer_7 = QTextEdit(Form)
        self.Korean_answer_7.setObjectName(u"Korean_answer_7")
        self.Korean_answer_7.setGeometry(QRect(180, 140, 71, 21))
        self.Korean_answer_6 = QTextEdit(Form)
        self.Korean_answer_6.setObjectName(u"Korean_answer_6")
        self.Korean_answer_6.setGeometry(QRect(180, 120, 71, 21))
        self.Korean_answer_3 = QTextEdit(Form)
        self.Korean_answer_3.setObjectName(u"Korean_answer_3")
        self.Korean_answer_3.setGeometry(QRect(180, 60, 71, 21))
        self.Korean_answer_8 = QTextEdit(Form)
        self.Korean_answer_8.setObjectName(u"Korean_answer_8")
        self.Korean_answer_8.setGeometry(QRect(180, 160, 71, 21))
        self.Korean_answer_9 = QTextEdit(Form)
        self.Korean_answer_9.setObjectName(u"Korean_answer_9")
        self.Korean_answer_9.setGeometry(QRect(180, 180, 71, 21))
        self.Korean_answer_11 = QTextEdit(Form)
        self.Korean_answer_11.setObjectName(u"Korean_answer_11")
        self.Korean_answer_11.setGeometry(QRect(180, 220, 71, 21))
        self.Korean_answer_10 = QTextEdit(Form)
        self.Korean_answer_10.setObjectName(u"Korean_answer_10")
        self.Korean_answer_10.setGeometry(QRect(180, 200, 71, 21))
        self.Korean_answer_14 = QTextEdit(Form)
        self.Korean_answer_14.setObjectName(u"Korean_answer_14")
        self.Korean_answer_14.setGeometry(QRect(180, 280, 71, 21))
        self.Korean_answer_13 = QTextEdit(Form)
        self.Korean_answer_13.setObjectName(u"Korean_answer_13")
        self.Korean_answer_13.setGeometry(QRect(180, 260, 71, 21))
        self.Korean_answer_12 = QTextEdit(Form)
        self.Korean_answer_12.setObjectName(u"Korean_answer_12")
        self.Korean_answer_12.setGeometry(QRect(180, 240, 71, 21))
        self.Korean_answer_16 = QTextEdit(Form)
        self.Korean_answer_16.setObjectName(u"Korean_answer_16")
        self.Korean_answer_16.setGeometry(QRect(180, 320, 71, 21))
        self.Korean_answer_15 = QTextEdit(Form)
        self.Korean_answer_15.setObjectName(u"Korean_answer_15")
        self.Korean_answer_15.setGeometry(QRect(180, 300, 71, 21))
        self.Korean_answer_17 = QTextEdit(Form)
        self.Korean_answer_17.setObjectName(u"Korean_answer_17")
        self.Korean_answer_17.setGeometry(QRect(180, 340, 71, 21))
        self.Korean_answer_19 = QTextEdit(Form)
        self.Korean_answer_19.setObjectName(u"Korean_answer_19")
        self.Korean_answer_19.setGeometry(QRect(180, 380, 71, 21))
        self.Korean_answer_18 = QTextEdit(Form)
        self.Korean_answer_18.setObjectName(u"Korean_answer_18")
        self.Korean_answer_18.setGeometry(QRect(180, 360, 71, 21))
        self.Korean_answer_20 = QTextEdit(Form)
        self.Korean_answer_20.setObjectName(u"Korean_answer_20")
        self.Korean_answer_20.setGeometry(QRect(180, 400, 71, 21))
        self.Korean_answer_32 = QTextEdit(Form)
        self.Korean_answer_32.setObjectName(u"Korean_answer_32")
        self.Korean_answer_32.setGeometry(QRect(420, 240, 71, 21))
        self.Korean_answer_30 = QTextEdit(Form)
        self.Korean_answer_30.setObjectName(u"Korean_answer_30")
        self.Korean_answer_30.setGeometry(QRect(420, 200, 71, 21))
        self.Korean_answer_28 = QTextEdit(Form)
        self.Korean_answer_28.setObjectName(u"Korean_answer_28")
        self.Korean_answer_28.setGeometry(QRect(420, 160, 71, 21))
        self.Korean_answer_33 = QTextEdit(Form)
        self.Korean_answer_33.setObjectName(u"Korean_answer_33")
        self.Korean_answer_33.setGeometry(QRect(420, 260, 71, 21))
        self.Korean_answer_40 = QTextEdit(Form)
        self.Korean_answer_40.setObjectName(u"Korean_answer_40")
        self.Korean_answer_40.setGeometry(QRect(420, 400, 71, 21))
        self.Korean_answer_39 = QTextEdit(Form)
        self.Korean_answer_39.setObjectName(u"Korean_answer_39")
        self.Korean_answer_39.setGeometry(QRect(420, 380, 71, 21))
        self.Korean_answer_25 = QTextEdit(Form)
        self.Korean_answer_25.setObjectName(u"Korean_answer_25")
        self.Korean_answer_25.setGeometry(QRect(420, 100, 71, 21))
        self.Korean_answer_27 = QTextEdit(Form)
        self.Korean_answer_27.setObjectName(u"Korean_answer_27")
        self.Korean_answer_27.setGeometry(QRect(420, 140, 71, 21))
        self.Korean_answer_21 = QTextEdit(Form)
        self.Korean_answer_21.setObjectName(u"Korean_answer_21")
        self.Korean_answer_21.setGeometry(QRect(420, 20, 71, 21))
        self.Korean_answer_37 = QTextEdit(Form)
        self.Korean_answer_37.setObjectName(u"Korean_answer_37")
        self.Korean_answer_37.setGeometry(QRect(420, 340, 71, 21))
        self.Korean_answer_24 = QTextEdit(Form)
        self.Korean_answer_24.setObjectName(u"Korean_answer_24")
        self.Korean_answer_24.setGeometry(QRect(420, 80, 71, 21))
        self.Korean_answer_31 = QTextEdit(Form)
        self.Korean_answer_31.setObjectName(u"Korean_answer_31")
        self.Korean_answer_31.setGeometry(QRect(420, 220, 71, 21))
        self.Korean_answer_34 = QTextEdit(Form)
        self.Korean_answer_34.setObjectName(u"Korean_answer_34")
        self.Korean_answer_34.setGeometry(QRect(420, 280, 71, 21))
        self.Korean_answer_23 = QTextEdit(Form)
        self.Korean_answer_23.setObjectName(u"Korean_answer_23")
        self.Korean_answer_23.setGeometry(QRect(420, 60, 71, 21))
        self.Korean_answer_36 = QTextEdit(Form)
        self.Korean_answer_36.setObjectName(u"Korean_answer_36")
        self.Korean_answer_36.setGeometry(QRect(420, 320, 71, 21))
        self.Korean_answer_22 = QTextEdit(Form)
        self.Korean_answer_22.setObjectName(u"Korean_answer_22")
        self.Korean_answer_22.setGeometry(QRect(420, 40, 71, 21))
        self.Korean_answer_29 = QTextEdit(Form)
        self.Korean_answer_29.setObjectName(u"Korean_answer_29")
        self.Korean_answer_29.setGeometry(QRect(420, 180, 71, 21))
        self.Korean_answer_35 = QTextEdit(Form)
        self.Korean_answer_35.setObjectName(u"Korean_answer_35")
        self.Korean_answer_35.setGeometry(QRect(420, 300, 71, 21))
        self.Korean_answer_26 = QTextEdit(Form)
        self.Korean_answer_26.setObjectName(u"Korean_answer_26")
        self.Korean_answer_26.setGeometry(QRect(420, 120, 71, 21))
        self.Korean_answer_38 = QTextEdit(Form)
        self.Korean_answer_38.setObjectName(u"Korean_answer_38")
        self.Korean_answer_38.setGeometry(QRect(420, 360, 71, 21))
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(500, 380, 101, 41))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(510, 350, 91, 16))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\ucc44\uc810\ud558\uae30", None))
        self.label.setText(QCoreApplication.translate("Form", u"TextLabel", None))
    # retranslateUi

