# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ele.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QListWidget, QListWidgetItem,
    QPushButton, QSizePolicy, QTextEdit, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(606, 456)
        self.listWidget = QListWidget(Form)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(110, 20, 61, 401))
        self.listWidget_2 = QListWidget(Form)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(340, 20, 71, 401))
        self.listWidget_3 = QListWidget(Form)
        self.listWidget_3.setObjectName(u"listWidget_3")
        self.listWidget_3.setGeometry(QRect(260, 20, 71, 401))
        self.listWidget_4 = QListWidget(Form)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(30, 20, 71, 401))
        self.textEdit = QTextEdit(Form)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(180, 20, 71, 21))
        self.textEdit_2 = QTextEdit(Form)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(180, 80, 71, 21))
        self.textEdit_3 = QTextEdit(Form)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(180, 100, 71, 21))
        self.textEdit_4 = QTextEdit(Form)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(180, 40, 71, 21))
        self.textEdit_5 = QTextEdit(Form)
        self.textEdit_5.setObjectName(u"textEdit_5")
        self.textEdit_5.setGeometry(QRect(180, 140, 71, 21))
        self.textEdit_6 = QTextEdit(Form)
        self.textEdit_6.setObjectName(u"textEdit_6")
        self.textEdit_6.setGeometry(QRect(180, 120, 71, 21))
        self.textEdit_7 = QTextEdit(Form)
        self.textEdit_7.setObjectName(u"textEdit_7")
        self.textEdit_7.setGeometry(QRect(180, 60, 71, 21))
        self.textEdit_8 = QTextEdit(Form)
        self.textEdit_8.setObjectName(u"textEdit_8")
        self.textEdit_8.setGeometry(QRect(180, 160, 71, 21))
        self.textEdit_9 = QTextEdit(Form)
        self.textEdit_9.setObjectName(u"textEdit_9")
        self.textEdit_9.setGeometry(QRect(180, 180, 71, 21))
        self.textEdit_10 = QTextEdit(Form)
        self.textEdit_10.setObjectName(u"textEdit_10")
        self.textEdit_10.setGeometry(QRect(180, 220, 71, 21))
        self.textEdit_11 = QTextEdit(Form)
        self.textEdit_11.setObjectName(u"textEdit_11")
        self.textEdit_11.setGeometry(QRect(180, 200, 71, 21))
        self.textEdit_12 = QTextEdit(Form)
        self.textEdit_12.setObjectName(u"textEdit_12")
        self.textEdit_12.setGeometry(QRect(180, 280, 71, 21))
        self.textEdit_13 = QTextEdit(Form)
        self.textEdit_13.setObjectName(u"textEdit_13")
        self.textEdit_13.setGeometry(QRect(180, 260, 71, 21))
        self.textEdit_14 = QTextEdit(Form)
        self.textEdit_14.setObjectName(u"textEdit_14")
        self.textEdit_14.setGeometry(QRect(180, 240, 71, 21))
        self.textEdit_15 = QTextEdit(Form)
        self.textEdit_15.setObjectName(u"textEdit_15")
        self.textEdit_15.setGeometry(QRect(180, 320, 71, 21))
        self.textEdit_16 = QTextEdit(Form)
        self.textEdit_16.setObjectName(u"textEdit_16")
        self.textEdit_16.setGeometry(QRect(180, 300, 71, 21))
        self.textEdit_17 = QTextEdit(Form)
        self.textEdit_17.setObjectName(u"textEdit_17")
        self.textEdit_17.setGeometry(QRect(180, 340, 71, 21))
        self.textEdit_18 = QTextEdit(Form)
        self.textEdit_18.setObjectName(u"textEdit_18")
        self.textEdit_18.setGeometry(QRect(180, 380, 71, 21))
        self.textEdit_19 = QTextEdit(Form)
        self.textEdit_19.setObjectName(u"textEdit_19")
        self.textEdit_19.setGeometry(QRect(180, 360, 71, 21))
        self.textEdit_20 = QTextEdit(Form)
        self.textEdit_20.setObjectName(u"textEdit_20")
        self.textEdit_20.setGeometry(QRect(180, 400, 71, 21))
        self.textEdit_21 = QTextEdit(Form)
        self.textEdit_21.setObjectName(u"textEdit_21")
        self.textEdit_21.setGeometry(QRect(420, 240, 71, 21))
        self.textEdit_22 = QTextEdit(Form)
        self.textEdit_22.setObjectName(u"textEdit_22")
        self.textEdit_22.setGeometry(QRect(420, 200, 71, 21))
        self.textEdit_23 = QTextEdit(Form)
        self.textEdit_23.setObjectName(u"textEdit_23")
        self.textEdit_23.setGeometry(QRect(420, 160, 71, 21))
        self.textEdit_24 = QTextEdit(Form)
        self.textEdit_24.setObjectName(u"textEdit_24")
        self.textEdit_24.setGeometry(QRect(420, 260, 71, 21))
        self.textEdit_25 = QTextEdit(Form)
        self.textEdit_25.setObjectName(u"textEdit_25")
        self.textEdit_25.setGeometry(QRect(420, 400, 71, 21))
        self.textEdit_26 = QTextEdit(Form)
        self.textEdit_26.setObjectName(u"textEdit_26")
        self.textEdit_26.setGeometry(QRect(420, 380, 71, 21))
        self.textEdit_27 = QTextEdit(Form)
        self.textEdit_27.setObjectName(u"textEdit_27")
        self.textEdit_27.setGeometry(QRect(420, 100, 71, 21))
        self.textEdit_28 = QTextEdit(Form)
        self.textEdit_28.setObjectName(u"textEdit_28")
        self.textEdit_28.setGeometry(QRect(420, 140, 71, 21))
        self.textEdit_29 = QTextEdit(Form)
        self.textEdit_29.setObjectName(u"textEdit_29")
        self.textEdit_29.setGeometry(QRect(420, 20, 71, 21))
        self.textEdit_30 = QTextEdit(Form)
        self.textEdit_30.setObjectName(u"textEdit_30")
        self.textEdit_30.setGeometry(QRect(420, 340, 71, 21))
        self.textEdit_31 = QTextEdit(Form)
        self.textEdit_31.setObjectName(u"textEdit_31")
        self.textEdit_31.setGeometry(QRect(420, 80, 71, 21))
        self.textEdit_32 = QTextEdit(Form)
        self.textEdit_32.setObjectName(u"textEdit_32")
        self.textEdit_32.setGeometry(QRect(420, 220, 71, 21))
        self.textEdit_33 = QTextEdit(Form)
        self.textEdit_33.setObjectName(u"textEdit_33")
        self.textEdit_33.setGeometry(QRect(420, 280, 71, 21))
        self.textEdit_34 = QTextEdit(Form)
        self.textEdit_34.setObjectName(u"textEdit_34")
        self.textEdit_34.setGeometry(QRect(420, 60, 71, 21))
        self.textEdit_35 = QTextEdit(Form)
        self.textEdit_35.setObjectName(u"textEdit_35")
        self.textEdit_35.setGeometry(QRect(420, 320, 71, 21))
        self.textEdit_36 = QTextEdit(Form)
        self.textEdit_36.setObjectName(u"textEdit_36")
        self.textEdit_36.setGeometry(QRect(420, 40, 71, 21))
        self.textEdit_37 = QTextEdit(Form)
        self.textEdit_37.setObjectName(u"textEdit_37")
        self.textEdit_37.setGeometry(QRect(420, 180, 71, 21))
        self.textEdit_38 = QTextEdit(Form)
        self.textEdit_38.setObjectName(u"textEdit_38")
        self.textEdit_38.setGeometry(QRect(420, 300, 71, 21))
        self.textEdit_39 = QTextEdit(Form)
        self.textEdit_39.setObjectName(u"textEdit_39")
        self.textEdit_39.setGeometry(QRect(420, 120, 71, 21))
        self.textEdit_40 = QTextEdit(Form)
        self.textEdit_40.setObjectName(u"textEdit_40")
        self.textEdit_40.setGeometry(QRect(420, 360, 71, 21))
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(500, 380, 101, 41))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(510, 350, 91, 16))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\ucc44\uc810\ud558\uae30", None))
        self.label.setText(QCoreApplication.translate("Form", u"TextLabel", None))
    # retranslateUi

