# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ele.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QPushButton, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(731, 415)
        self.listWidget_2 = QListWidget(Form)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(110, 10, 91, 401))
        self.listWidget_4 = QListWidget(Form)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(410, 10, 91, 401))
        self.En_word_3 = QListWidget(Form)
        self.En_word_3.setObjectName(u"En_word_3")
        self.En_word_3.setGeometry(QRect(300, 10, 111, 401))
        self.En_word_1 = QListWidget(Form)
        self.En_word_1.setObjectName(u"En_word_1")
        self.En_word_1.setGeometry(QRect(0, 10, 111, 401))
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(600, 360, 131, 51))
        self.Time_limit = QLabel(Form)
        self.Time_limit.setObjectName(u"Time_limit")
        self.Time_limit.setGeometry(QRect(610, 335, 101, 21))
        font = QFont()
        font.setPointSize(12)
        self.Time_limit.setFont(font)
        self.kr_answer_1 = QLineEdit(Form)
        self.kr_answer_1.setObjectName(u"kr_answer_1")
        self.kr_answer_1.setGeometry(QRect(210, 10, 81, 20))
        self.kr_answer_2 = QLineEdit(Form)
        self.kr_answer_2.setObjectName(u"kr_answer_2")
        self.kr_answer_2.setGeometry(QRect(210, 30, 81, 20))
        self.kr_answer_3 = QLineEdit(Form)
        self.kr_answer_3.setObjectName(u"kr_answer_3")
        self.kr_answer_3.setGeometry(QRect(210, 50, 81, 20))
        self.kr_answer_4 = QLineEdit(Form)
        self.kr_answer_4.setObjectName(u"kr_answer_4")
        self.kr_answer_4.setGeometry(QRect(210, 70, 81, 20))
        self.kr_answer_5 = QLineEdit(Form)
        self.kr_answer_5.setObjectName(u"kr_answer_5")
        self.kr_answer_5.setGeometry(QRect(210, 90, 81, 20))
        self.kr_answer_6 = QLineEdit(Form)
        self.kr_answer_6.setObjectName(u"kr_answer_6")
        self.kr_answer_6.setGeometry(QRect(210, 110, 81, 20))
        self.kr_answer_7 = QLineEdit(Form)
        self.kr_answer_7.setObjectName(u"kr_answer_7")
        self.kr_answer_7.setGeometry(QRect(210, 130, 81, 20))
        self.kr_answer_8 = QLineEdit(Form)
        self.kr_answer_8.setObjectName(u"kr_answer_8")
        self.kr_answer_8.setGeometry(QRect(210, 150, 81, 20))
        self.kr_answer_9 = QLineEdit(Form)
        self.kr_answer_9.setObjectName(u"kr_answer_9")
        self.kr_answer_9.setGeometry(QRect(210, 170, 81, 20))
        self.kr_answer_10 = QLineEdit(Form)
        self.kr_answer_10.setObjectName(u"kr_answer_10")
        self.kr_answer_10.setGeometry(QRect(210, 190, 81, 20))
        self.kr_answer_11 = QLineEdit(Form)
        self.kr_answer_11.setObjectName(u"kr_answer_11")
        self.kr_answer_11.setGeometry(QRect(210, 210, 81, 20))
        self.kr_answer_12 = QLineEdit(Form)
        self.kr_answer_12.setObjectName(u"kr_answer_12")
        self.kr_answer_12.setGeometry(QRect(210, 230, 81, 20))
        self.kr_answer_13 = QLineEdit(Form)
        self.kr_answer_13.setObjectName(u"kr_answer_13")
        self.kr_answer_13.setGeometry(QRect(210, 250, 81, 20))
        self.kr_answer_14 = QLineEdit(Form)
        self.kr_answer_14.setObjectName(u"kr_answer_14")
        self.kr_answer_14.setGeometry(QRect(210, 270, 81, 20))
        self.kr_answer_15 = QLineEdit(Form)
        self.kr_answer_15.setObjectName(u"kr_answer_15")
        self.kr_answer_15.setGeometry(QRect(210, 290, 81, 20))
        self.kr_answer_16 = QLineEdit(Form)
        self.kr_answer_16.setObjectName(u"kr_answer_16")
        self.kr_answer_16.setGeometry(QRect(210, 310, 81, 20))
        self.kr_answer_17 = QLineEdit(Form)
        self.kr_answer_17.setObjectName(u"kr_answer_17")
        self.kr_answer_17.setGeometry(QRect(210, 330, 81, 20))
        self.kr_answer_18 = QLineEdit(Form)
        self.kr_answer_18.setObjectName(u"kr_answer_18")
        self.kr_answer_18.setGeometry(QRect(210, 350, 81, 20))
        self.kr_answer_19 = QLineEdit(Form)
        self.kr_answer_19.setObjectName(u"kr_answer_19")
        self.kr_answer_19.setGeometry(QRect(210, 370, 81, 20))
        self.kr_answer_20 = QLineEdit(Form)
        self.kr_answer_20.setObjectName(u"kr_answer_20")
        self.kr_answer_20.setGeometry(QRect(210, 390, 81, 20))
        self.kr_answer_21 = QLineEdit(Form)
        self.kr_answer_21.setObjectName(u"kr_answer_21")
        self.kr_answer_21.setGeometry(QRect(510, 10, 81, 20))
        self.kr_answer_22 = QLineEdit(Form)
        self.kr_answer_22.setObjectName(u"kr_answer_22")
        self.kr_answer_22.setGeometry(QRect(510, 30, 81, 20))
        self.kr_answer_23 = QLineEdit(Form)
        self.kr_answer_23.setObjectName(u"kr_answer_23")
        self.kr_answer_23.setGeometry(QRect(510, 50, 81, 20))
        self.kr_answer_24 = QLineEdit(Form)
        self.kr_answer_24.setObjectName(u"kr_answer_24")
        self.kr_answer_24.setGeometry(QRect(510, 70, 81, 20))
        self.kr_answer_25 = QLineEdit(Form)
        self.kr_answer_25.setObjectName(u"kr_answer_25")
        self.kr_answer_25.setGeometry(QRect(510, 90, 81, 20))
        self.kr_answer_26 = QLineEdit(Form)
        self.kr_answer_26.setObjectName(u"kr_answer_26")
        self.kr_answer_26.setGeometry(QRect(510, 110, 81, 20))
        self.kr_answer_27 = QLineEdit(Form)
        self.kr_answer_27.setObjectName(u"kr_answer_27")
        self.kr_answer_27.setGeometry(QRect(510, 130, 81, 20))
        self.kr_answer_28 = QLineEdit(Form)
        self.kr_answer_28.setObjectName(u"kr_answer_28")
        self.kr_answer_28.setGeometry(QRect(510, 150, 81, 20))
        self.kr_answer_29 = QLineEdit(Form)
        self.kr_answer_29.setObjectName(u"kr_answer_29")
        self.kr_answer_29.setGeometry(QRect(510, 170, 81, 20))
        self.kr_answer_30 = QLineEdit(Form)
        self.kr_answer_30.setObjectName(u"kr_answer_30")
        self.kr_answer_30.setGeometry(QRect(510, 190, 81, 20))
        self.kr_answer_31 = QLineEdit(Form)
        self.kr_answer_31.setObjectName(u"kr_answer_31")
        self.kr_answer_31.setGeometry(QRect(510, 210, 81, 20))
        self.kr_answer_32 = QLineEdit(Form)
        self.kr_answer_32.setObjectName(u"kr_answer_32")
        self.kr_answer_32.setGeometry(QRect(510, 230, 81, 20))
        self.kr_answer_33 = QLineEdit(Form)
        self.kr_answer_33.setObjectName(u"kr_answer_33")
        self.kr_answer_33.setGeometry(QRect(510, 250, 81, 20))
        self.kr_answer_34 = QLineEdit(Form)
        self.kr_answer_34.setObjectName(u"kr_answer_34")
        self.kr_answer_34.setGeometry(QRect(510, 270, 81, 20))
        self.kr_answer_35 = QLineEdit(Form)
        self.kr_answer_35.setObjectName(u"kr_answer_35")
        self.kr_answer_35.setGeometry(QRect(510, 290, 81, 20))
        self.kr_answer_36 = QLineEdit(Form)
        self.kr_answer_36.setObjectName(u"kr_answer_36")
        self.kr_answer_36.setGeometry(QRect(510, 310, 81, 20))
        self.kr_answer_37 = QLineEdit(Form)
        self.kr_answer_37.setObjectName(u"kr_answer_37")
        self.kr_answer_37.setGeometry(QRect(510, 330, 81, 20))
        self.kr_answer_38 = QLineEdit(Form)
        self.kr_answer_38.setObjectName(u"kr_answer_38")
        self.kr_answer_38.setGeometry(QRect(510, 350, 81, 20))
        self.kr_answer_39 = QLineEdit(Form)
        self.kr_answer_39.setObjectName(u"kr_answer_39")
        self.kr_answer_39.setGeometry(QRect(510, 370, 81, 20))
        self.kr_answer_40 = QLineEdit(Form)
        self.kr_answer_40.setObjectName(u"kr_answer_40")
        self.kr_answer_40.setGeometry(QRect(510, 390, 81, 20))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\ucc44\uc810\ud558\uae30", None))
        self.Time_limit.setText(QCoreApplication.translate("Form", u"00:00:00", None))
    # retranslateUi

